### ISSUE TITLE
StepIn, StepInto and StepOut don't work

### ISSUE THREAD

**Issue by InDIOS** [hbenl/vscode-firefox-debug#1]
Hi, i was looking for this a long time ago and i'm very thankful, but i found a bug when i try to use the stepin, stepinto or stepout, nothing happens when click on one of these actions, everything works except the actions that i mentioned.
I'm using vscode 1.1.0 in windows 10, firefox 46.0.1 and the latest version of this pluging. I hope help

**Comment by hbenl** [comment]
Hi, I tried to reproduce this but stepping worked for me. I tested this with VS Code 1.1.1 on Windows 7 and Firefox 45.0.1 - that's the closest I could get to your setup but I doubt that this has anything to do with the versions of Windows or Firefox.
Could you please make a test page available together with the exact steps how to reproduce (e.g. the location of your breakpoint, what to click on the page to trigger the breakpoint ...).

**Comment by InDIOS** [comment]
These is the image.
![the_picture](https://cloud.githubusercontent.com/assets/11496916/15930916/9be4b96e-2e55-11e6-806b-37f3ab11858e.png)

**Comment by hbenl** [comment]
Sorry, that's still not enough information for me to reproduce the problem.
Could you make a zip file containing your web application and attach it to this thread?

**Comment by InDIOS** [comment]
Hi again, sorry but i can't give you a copy of the project because isn't permitted for me, but i have made an tiny example that doesn't work too. I omitted that the continue button doesn't work neither. I tried this

index.html
<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
	&lt;meta charset=&quot;UTF-8&quot;&gt;
	&lt;title&gt;Sample&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
	&lt;div id=&quot;sample&quot;&gt;&lt;/div&gt;
	&lt;script src=&quot;./script.js&quot;&gt;&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>
and
script.js
<pre>
(function () {
	var sample = document.getElementById('sample');
	var tag = sample.tagName;
	console.log(tag);
})();
</pre>
Put a breakpoint wherever you want and try to debug.

**Comment by hbenl** [comment]
Thanks, now I could reproduce the bug and fix it. Please update your plugin and confirm if it works in your web application as well.

**Comment by InDIOS** [comment]
Everything works fine now, thank you for be so faster.

**Comment by hbenl** [comment]
Great. Thanks for the bugreport.
