### ISSUE TITLE
unable to lounch >1 debug sessions

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#10]
If I want to debug 2 different projects in 2 different VSC instances I get the following error:
```
Error: EBUSY: resource busy or locked, unlink '%USERPROFILE%\AppData\Local\Temp\vscode-firefox-debug-profile\cert8.db'
```
Obviously the temp profile should get a uuid in the name.

And/Or maybe instead using temp, the profile could be stored in the ``.vscode`` folder (when a launch config says so, like ``"localProfile": true``)? ``.vscode`` is often gitignored so it shouldn't be a problem. Additionally that way Firefox staff would persist between lounches without the need for the user creating a dedicated profile. "profileName" option should override "localProfile" though.

**Comment by hbenl** [comment]
I will make the names of the temporary profiles unique in the next version.
If you want to have the profile stored permanently (and/or in some other place) without having to create a dedicated profile yourself, you can use the `profileDir` option. The profile will still be automatically created and configured for remote debugging if it doesn't exist yet.

**Comment by Spown** [comment]
> ``profileDir`` option

Totally forgot about it. Yes, this will do. thnx
