### ISSUE TITLE
Typescript breakpoints not hit

### ISSUE THREAD

**Issue by duzenko** [hbenl/vscode-firefox-debug#101]
Attached is the minimal repro case that I can't ever get to hit breakpoints
I set a break at line 2 in a.ts ( `return "Hello, " + person;` ).
I have two configurations in launch.js - FF and Chrome.
Chrome "just works" and VSCode always stops on the breakpoint.
But when running in FF VScode never stops there.
What am I missing here?
[ff66ts.zip](https://github.com/hbenl/vscode-firefox-debug/files/2988277/ff66ts.zip)
FWIW my Firefox installation is version 66 (32 bit) and I have checked "Enable add-on debugging" in about:debugging. Did not try other versions.
Please note that 'regular' JS works just fine - it's the TypeScript code that fails to stop.

**Comment by hbenl** [comment]
I just fixed this in version 1.7.8.
(Firefox 67 made some debug protocol changes and the adapter wrongly identified Firefox 66 as having the changed protocol)
