### ISSUE TITLE
How to use the default profile not a new one

### ISSUE THREAD

**Issue by velara3** [hbenl/vscode-firefox-debug#105]
When I launch a debug session Firefox is starting with a new profile. How do I have it use my default profile without keeping any changes? 

I've read about this setting and it sounds like what I want.

>profileDir, profile: You can specify a Firefox profile directory or the name of a profile created with the Firefox profile manager. The extension will create a copy of this profile in the system's temporary directory and modify the settings in this copy to allow remote debugging. You can also override these properties in your settings (see below).

>_"The extension will create a copy of this profile in the system's temporary directory and modify the settings..."_

That is what I'd like to do but I don't know how to set this up. I don't have a profile setup on Firefox. I'd like it to use the default. I'm using the developer edition on OSX.

Here's what I have so far: 

      {
         "name": "Launch index.html",
         "type": "firefox",
         "request": "launch",
         "reAttach": true,
         "file": "${workspaceFolder}/index.html"
      },

**Comment by hbenl** [comment]
try `"profile": "default"`. If that doesn't work, launch Firefox from the command line with `firefox -P` or `firefox --ProfileManager` - this will open the profile manager showing all your profiles with their names (usually there is one profile called "default").
