### ISSUE TITLE
Output filtering

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#11]
It doesn't seem like ``log.consoleLevel.default`` is working. Even if I set it to ``"Error"`` I still get ``"Warn"`` level staff.

Currently vscode-firefox-debug passes absolutly everything Firefox logs, however even the FF's web console standard setting hides some unimportant staff, for example in my case this is how web console looks:

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-09/firefox_2016-09-04_10-05-50.png)

and this what VSC Debug Console shows (most of the garbage are css warnings):
```
Error in parsing value for 'display'.  Declaration dropped.
Error in parsing value for 'justify-content'.  Declaration dropped.
Error in parsing value for 'justify-content'.  Declaration dropped.
Error in parsing value for 'justify-content'.  Declaration dropped.
Error in parsing value for 'width'.  Declaration dropped.
Error in parsing value for 'width'.  Declaration dropped.
Error in parsing value for 'width'.  Declaration dropped.
Error in parsing value for 'width'.  Declaration dropped.
ready!
ready 2
Unknown property '-moz-border-radius'.  Declaration dropped.
Expected declaration but found '*'.  Skipped to next declaration.
Expected declaration but found '*'.  Skipped to next declaration.
Unknown property '-moz-border-radius'.  Declaration dropped.
Expected declaration but found '*'.  Skipped to next declaration.
Expected declaration but found '*'.  Skipped to next declaration.
Expected declaration but found '*'.  Skipped to next declaration.
Unknown property '-moz-border-radius'.  Declaration dropped.
Unknown property '-moz-border-radius'.  Declaration dropped.
Unknown property '-moz-border-radius'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Expected color but found 'top'.  Error in parsing value for 'background'.  Declaration dropped.
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Unknown property '-moz-border-radius'.  Declaration dropped.
Unknown property '-moz-box-shadow'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Error in parsing value for 'background'.  Declaration dropped.
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped.
Error in parsing value for 'background-position'.  Declaration dropped.
```

Maybe it could be possible to make vscode-firefox-debug respect the FF's web console filter settings and show exactly the same that web console shows?

**Comment by hbenl** [comment]
There are 2 kinds of messages sent to the VS Code console:
- console messages from Firefox - these are currently simply passed on without any filtering
- diagnostic messages from the extension itself - these are filtered according to `log.consoleLevel` and `log.fileLevel` properties

When you say that you can still see "Warn" level messages, are these from Firefox or from the extension? The extension messages always start with something like `DEBUG|001.145|PathConversion:`.

I still have to figure out how to filter the Firefox messages properly - Firefox sends a lot of information with each of these messages and all of it is undocumented...

**Comment by Spown** [comment]
>When you say that you can still see "Warn" level messages, are these from Firefox or from the extension? The extension messages always start with something like DEBUG|001.145|PathConversion:.

from Firefox. Extension's messages I can filter just fine. These ones in the example are all CSS messages  of  Warning level, but as they appear in VSC output they seem to become >= "Error" (both when I set ``"log.consoleLevel.default": "Error"`` or leave ``log.consoleLevel.default`` out for default to take effect)

**Comment by hbenl** [comment]
Only javascript-related warnings and errors from Firefox will now be shown in the VSC debug console.
Since this adapter doesn't implement any of the non-javascript-related features of the Firefox developer tools, it probably doesn't make much sense to show any other messages.
