### ISSUE TITLE
Firefox is not launched on a Mac

### ISSUE THREAD

**Issue by erdennis13** [hbenl/vscode-firefox-debug#110]
Recently the extension is failing to launch or attach to Firefox on a Mac. When starting a debugging session Firefox becomes unresponsive and has to be force quit.

I've confirmed the debug configuration works on a Windows machine.

**Comment by hbenl** [comment]
Sorry for the delay, I don't own a Mac... 
This should be fixed in version 1.8.3, which I just released. Please report here if it works for you.

**Comment by erdennis13** [comment]
It's working again - thanks for the quick response!
