### ISSUE TITLE
Second page reload breaks on the next line

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#12]
[Test case](/Spown/vsc_ff_debug_test_webapp/commit/9f19d8ed569b96336cae1b05f896674516c74f53).
The first time I realod a page the break occurs on the breakpoint line. Second (and every subsequent) page reload breaks on line right after the breakpoit.

**Comment by hbenl** [comment]
Fixed in 0.6.4. Thanks for the report and test case.
