### ISSUE TITLE
"parsing failed,[object Object]" in Debug Console

### ISSUE THREAD

**Issue by jnachtigall** [hbenl/vscode-firefox-debug#13]
I regularly get a `parsing failed,[object Object]` in the Debug Console of VS Code, which I find kind of irritating: I had a problem to get the Debugger started, and thought this might be related. Turned out that this error message had nothing to do with it.

I'd propose:
a) either do not log this message (maybe vs code has some kind of log level?). In its current form its not helpful.
b) or make the message text a bit more meaningful (what's inside the object? what was tried to be parsed?).

**Comment by hbenl** [comment]
Hmm, I don't know where this message comes from or how it ends up in the debug console. I only send messages to the console that come from Firefox or my adapter (and in the latest version of the adapter the latter never show up unless they're explicitly configured using the `log` configuration property).
Do you have a test case for this? I'd like to track this down because it may point to something going wrong that could cause more trouble down the line.

**Comment by jnachtigall** [comment]
hey, here's a test case to reproduce:
[parsingfailed.zip](https://github.com/hbenl/vscode-firefox-debug/files/502889/parsingfailed.zip)
I could not get the warning with the minimal test case as given in https://github.com/hbenl/vscode-firefox-debug/issues/14#issuecomment-250726690 so it probably includes some unneeded stuff as well.

Anyway, just unzip, cd into the project folder and start a webserver, e.g. with ` python -m SimpleHTTPServer 8082`. Then open the project folder in VS and launch `Fx: Launch localhost`. You do not acually need to set any breakpoint to get the warning:
![2016-09-30 14_14_09-parsingfailed - visual studio code](https://cloud.githubusercontent.com/assets/3307404/18991339/3767520a-8718-11e6-91b5-824e52196e30.png)

Edit: I'm just getting this warning using the Fx Developer Edition (which is Aurora 51.0a2 (2016-09-29)), but not the current release version 49. I just noticed now. Anyway, it would still worthwhile to:
1. Make the 'parsing failed' warning a bit more verbose (which Message was not parsed successfully)
2. Still fix the error as Version 51 while hit Release in 12 weeks.

**Comment by hbenl** [comment]
The message apparently comes from the file `src/js/components/map/heatmapLayer.js` in your project:
```
...
      }).catch(function(ex) {
        console.log('parsing failed', ex);
      });
```
The second argument to the console.log call is an object and since I can only send strings to the debug console, it shows up as `[object Object]`.

**Comment by jnachtigall** [comment]
hui, that's, well, embarrassing  :running: Sorry for the hassle

**Comment by hbenl** [comment]
No problem :smile:
