### ISSUE TITLE
Breakpoints in sourcemapped files do not work

### ISSUE THREAD

**Issue by jnachtigall** [hbenl/vscode-firefox-debug#14]
> Sourcemaps - these are handled by Firefox, so if they work in the built-in Firefox debugger, they should also work in VS Code

My sourcemaps work in the builtin Firefox debugger and also in the Chrome debugger extension of VS Code. However, they do not work with this Firefox extension :-/ (Not even on second reload.)

I use Firefox Developer Edition 51.0a2 (2016-09-28) (64-bit)

If you cannot reproduce then I could prepare a minimal test case (don't have time now).

**Comment by hbenl** [comment]
I couldn't reproduce this, so a test case would be very much appreciated.

**Comment by jnachtigall** [comment]
Here's a minimal testcase: 
[testcase.zip](https://github.com/hbenl/vscode-firefox-debug/files/502855/testcase.zip)

**1. Unzip.** 
There's a dist/ and a src/ folder

The included file in the index.html is dist/js/app.js which in this case is just the same like src/js/app.js. The dist/js/app.js.map maps it to the source at src/js/app.js (To keep it simple there's no uglification of the JS, so the map file is almost human readable)

**2. Set a breakpoint in src/js/app.js in VS Code**

**3. Start a webserver in the root folder, e.g.**
```
# change to folder
cd testcase
# start a simple http server, could also be apache or something else
python -m SimpleHTTPServer 8082
```
**4. The actual debugging**
a) in VS Code launch the debugger named `Cr: Launch localhost` (the Chrome debugger extension). After page has initially loaded, do a reload (Chrome seems to have the same shortcomings like the Firefox debugger regarding initially setting a breakpoint ;) ). The breakpoint is hit and working.

b) **The actual bug:** Then do the same with `Fx: Launch localhost`. As said I am using the Firefox Developer Edition, so you might need to update the firefoxExecutable setting. Reload then 2nd time. Breakpoint is not hit and not working. 

c) In the debugger it also works, breakpoint is hit:
![2016-09-30 13_38_41-testcase - firefox developer edition](https://cloud.githubusercontent.com/assets/3307404/18990814/d4a3e8c0-8714-11e6-80dc-6bb92dade88e.png)

**Comment by hbenl** [comment]
Thanks! The reason is that the source is embedded in the sourcemap and Firefox behaves a bit differently in this case. The bugfix shouldn't be difficult.
In the meantime, you could try if it works if you don't embed the source in the sourcemap.

**Comment by hbenl** [comment]
I just published a new version that works for the testcase. Please test it and let me know if it also works for your project.

**Comment by jnachtigall** [comment]
Jepp, works. Thank you!

One small nit: When setting a breakpoint at line 1 at `"use strict";` it does not stop their in Firfeox, whereas it does with Chrome and the Chrome debugger extension.

**Comment by hbenl** [comment]
Great!
About not being able to break at the `"use strict";` statement: the same happens in the built-in Firefox debugger, so it's an issue with the Firefox debugger backend, not this adapter.
