### ISSUE TITLE
Cannot start up the debugger on win10.

### ISSUE THREAD

**Issue by skyfeiyun** [hbenl/vscode-firefox-debug#15]
After following the guidance from the readme, I can still not use this plugin for debugging my apps. Is there any addtional instructions?

**Comment by hbenl** [comment]
What are your symptoms exactly? Are you able to to launch Firefox with this extension? Can you set breakpoints and do they get hit? Etc...
In any case, it would be useful if you attach your `.vscode/launch.json` file and create a log file (as explained in the [Diagnostic logging](https://github.com/hbenl/vscode-firefox-debug#diagnostic-logging) section of the documentation) and attach that.

**Comment by jnachtigall** [comment]
@skyfeiyun I also found it worthwhile to check if it works with the Chrome debugger to rule out a misconfiguration: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome Often it's a problem sourcemaps, configs or whatever and not really a bug of this Firefox debug extension. Can you get the Chrome debugger running?

**Comment by hbenl** [comment]
No reply -> closing
