### ISSUE TITLE
FirefoxDebugSession: Failed stackTraceRequest: TypeError: Cannot read property 'getObjectGripAdapter' of undefined

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#16]
> ERROR|140.098|FirefoxDebugSession: Failed stackTraceRequest: TypeError: Cannot read property 'getObjectGripAdapter' of undefined

This happens 4 times out of 5 when I set a breakpoint in a function, that is executed deep down in an async chain. the funny thing, 1 time out of 5 it does work properly. When I turn `"consoleLevel": { "default":  "Warn" }` it seem to work more often. It almost looks like the extra time debug option takes to output info is enough for the adapter to load the needed object, that contains this `getObjectGripAdapter` property.

I probably can provide the test case, but it would require me to transfer like 1/3 of my current project into it, so if you can make sense out of it without - I'd rather not ^^.

**Comment by hbenl** [comment]
Well, I can't make sense of it yet, but I'll try to reproduce it. Do you use Promises or classic callback-based async calls? Do you have any more observations as to when this happens and when it doesn't? Also, a log file (with `"fileLevel": { "default": "Debug" }`) may be useful.

**Comment by Spown** [comment]
there is nothing else related in the log. I have a bunch of ``WARN |004.706|PathConversion`` mainly regarding scripts, who's url contains query parts, which do not seem to be related. I use jQuery (1.11.2) ``.then``. IIRC at some point jQuery tries to use Promise internally if the browser supports it, but I don't really know. Anyway if you use FF 49 and jQuery 1.11.2 you#ll probably end up with the same internls as me...

**Comment by hbenl** [comment]
So far I have been unable to reproduce this, but I'll do some refactoring soon, especially on one class that I suspect is responsible for this bug (the class coordinates various asynchronous operations and hence is the prime suspect for any bug that is timing-sensitive). So I hope I'll catch this bug then.

**Comment by dotcs** [comment]
We face the same problem in our current setup (Angular 2 application). For us this happens nearby in every interaction with the page, which makes debugging in VS Code via Firefox nearby impossible, whereas debugging in VS Code via Chrome (via [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)) works like a charm.
Let me know if I can provide more information or can do some testing for you to get this issue fixed.

**Comment by hbenl** [comment]
OK, I gave my code another long, hard stare and may have found the issue.
Please update and tell me if it works for you now. If it does, you should see a new warning message in the diagnostic log starting with "Unexpected object grip of type ...". If you see this log message please post it here because it contains an undocumented object from the Firefox debug protocol that I would like to know about.

**Comment by Spown** [comment]
Well, it seems to work properly now and the debug session remains responsive. With the same breackpoints as before. However I'm not getting this "Unexpected object grip of type ..." anywhere, despite my logfile quickly growing to several MBs size.

Thank you!

**Comment by dotcs** [comment]
Yes, it does work now. For me the debug session remains responsive, too.
I also get the log message that you've described:
```
INFO |078.991|FirefoxDebugSession: Thread server1.conn3.child1/27 paused , reason: breakpoint
WARN |079.474|VariableAdapter: Unexpected object grip of type symbol: {"type":"symbol","name":"Symbol.iterator"}
WARN |079.477|VariableAdapter: Unexpected object grip of type symbol: {"type":"symbol","name":"Symbol.iterator"}
WARN |079.478|VariableAdapter: Unexpected object grip of type symbol: {"type":"symbol","name":"Symbol.iterator"}
```
Does that help?

**Comment by Spown** [comment]
I also get those ``ERROR|079.760|ObjectGripActorProxy: No such actor``. Quite a lot actually. However they seem to appear alongside with the actual script errors and do not hinder debugging process... at least not visibly.

**Comment by hbenl** [comment]
@dotcs : yes, that helps. Now I know how to reproduce this and how to fix it properly.

The "No such actor" messages are actually about a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1249962). I will change the log message to make this clear.

**Comment by dotcs** [comment]
@hbenl : Awesome! Thanks for your support, keep up the good work and let me know in case I can do anything else to support you.
