### ISSUE TITLE
Pleas add a describtion and link at github

### ISSUE THREAD

**Issue by jnachtigall** [hbenl/vscode-firefox-debug#2]
You should add a short description and link at this github project. Now it's "No description or website provided." at https://github.com/hbenl/vscode-firefox-debug

Maybe: 
"VS Code Debug Adapter for Firefox - https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-firefox-debug"

Makes it easier for new "Woo, what's this about?!?" users and looks better ;)

**Comment by hbenl** [comment]
Done. Thanks for the suggestion :)
