### ISSUE TITLE
vscode-firefox-debug + webpack devserver + typescript

### ISSUE THREAD

**Issue by mzygmunt** [hbenl/vscode-firefox-debug#22]
Hello @hbenl,
Thank you for your hard work on the extension. Can you make a working example of integration vscode-firefox-debug + webpack devserver (in memory) + typescript? I struggle with this for a few days and I have no ideas :(

**Comment by hbenl** [comment]
I haven't used webpack so far but want to use it in future projects, so I'd be interested in such an example myself. Could you publish your experimentations in a repository so I can have a look at it and figure out why it's not working?

**Comment by mzygmunt** [comment]
https://github.com/mzygmunt/vscode-firefox-debug-webpack-issue

It's simplified example of use webpack, react and react-hot-reload. Just clone, npm update, npm start and press F5. Everything will work, except debugging. It appears that vscode-firefox-debug has a problem with conversion of urls that begin with "webpack:///".

**Comment by hbenl** [comment]
You're right, the debug adapter doesn't know what to do with `webpack:///` URLs. The simplest solution for now is to tell webpack that it shouldn't add `webpack:///` to the URLs: in the plugin list in `start.js` replace `new webpack.SourceMapDevToolPlugin()` with
```
new webpack.SourceMapDevToolPlugin({
	moduleFilenameTemplate: '[resource-path]'
})
```
That works for me.
In the next version of the debug adapter I will add a configuration option that will let you add your own URL-to-path mappings, so you can tell the adapter to replace `webpack:///` with `${workspaceRoot}`.

**Comment by mzygmunt** [comment]
You're right, it works. Thank you for help. But have you noticed that refresh the page is a little slow?

**Comment by hbenl** [comment]
Yes, I noticed. But it doesn't seem to get much faster when I use Firefox' built-in debugger, so the performance problem doesn't seem to be related to this debug adapter.

**Comment by iskiselev** [comment]
It would be great if this option would work same way, as option for chrome debugger. Like:
```
"sourceMapPathOverrides": {
    "webpack:///./*":   "${webRoot}/*", // Example: "webpack:///./src/app.js" -> "/users/me/project/src/app.js"
    "webpack:///*":     "*",            // Example: "webpack:///C:/project/app.ts" -> "C:/project/app.ts"
    "meteor://💻app/*": "${webRoot}/*"  // Example: "meteor://💻app/main.ts" -> "c:/code/main.ts"
}
```
with support of `${workspaceRoot}` and `${webRoot}`

**Comment by hbenl** [comment]
I just released a new version of the debug adapter, you can now add a configuration property called `pathMappings`. In your test case, you can remove the `moduleFilenameTemplate` configuration property from the `SourceMapDevToolPlugin` constructor call and add this to `launch.json` instead:
```
"pathMappings": [
	{
		"url": "webpack:///",
		"path": "${webRoot}/"
	}
]
```
Note that `pathMappings` is similar but not identical to `sourceMapPathOverrides` for the Chrome Debugger: first of all, `sourceMapPathOverrides` is apparently only used when resolving sourcemaps, whereas `pathMappings` is always used to map URLs to local file paths. Second, `pathMappings` does not support any wildcard characters (it implicitly adds `*` at the end of both `url` and `path`).

**Comment by iskiselev** [comment]
I don't understand why, but it doesn't work for me.
I enabled console output for PathConversion with debug level. Now in console I see lots of lines like:
```
webpack:///opus/worker_app/polyfills.ts?cc3d*** to path <MyRealPath>\polyfills.ts?cc3d***
```
But, after it I don't see any sources on any breakpoint/exception anymore. Instead in Visual Studio Code developer console I see lot's of errors:
```
shell.ts:541 t.threads[n].getCachedCallStack is not a function: TypeError: t.threads[n].getCachedCallStack is not a function
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:84:16781
    at Array.forEach (native)
    at e.sourceIsUnavailable (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:84:16748)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:84:24710
    at Array.forEach (native)
    at e.sourceIsUnavailable (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:84:24681)
    at t.sourceIsUnavailable (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:128:12147)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:128:12058
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13263)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16768)
```

After some additional testing, I found that query parameter that were added to file are responsible for it. So, we either need some way to describe it in mapping, or strip it automatically if path was mapped.

**Comment by hbenl** [comment]
@iskiselev The latest version of the debug adapter now strips the query string from the url when converting it to a local file path. Please test and tell me if it works for you now.
