### ISSUE TITLE
Source File in Debug Console of VSCode

### ISSUE THREAD

**Issue by apazureck** [hbenl/vscode-firefox-debug#23]
Hello,

First of all, thank you for that great add-on. It is really just great.

I have a question / feature request:

The debugger console in firefox delivers the message and the source file/line/etc.

Would it be possible to display this in the vscode debug console as well?

Best regards

**Comment by hbenl** [comment]
Yes, that would be useful. I'd also like this to be a clickable link just as in the Firefox debug console, so I wrote a feature request for that (Microsoft/vscode-debugadapter-node#94). Once that is supported, I will add the feature to this debug adapter.

**Comment by apazureck** [comment]
That's great! Thank you very much.

**Comment by apazureck** [comment]
One question:
Have you tried handing it over with leading tabs or whitespaces? In general the console is able to expand or collapse entries:
![example collapse](https://cloud.githubusercontent.com/assets/14858596/21981650/bc90eb92-dbe8-11e6-84e4-704b51eda673.png)

If it works similar to the collapse and expand in the code window it would be possible to do that.

**Comment by hbenl** [comment]
No, I haven't tried this. But since a clickable link would be a lot nicer anyway, I'll wait for the linked feature request if it gets implemented soon.

**Comment by hbenl** [comment]
I have added a new configuration option `showConsoleCallLocation` that appends the source location of `console` calls to their output. It turns out that VS Code already converts them to clickable links.
