### ISSUE TITLE
Setting up launch config for CMS (WebServer) delivered JS

### ISSUE THREAD

**Issue by jnachtigall** [hbenl/vscode-firefox-debug#24]
This is not really a issue in the sense of a bugreport (maybe missing docs only). Anyway, I am struggling with the use case where a js file is delivered from within a complex server setup and I cannot figure out how to setup the launch configurition. Here's the case:

* The JS file to debug is at `\dist\themes\myproject\concat\production.js` within VSCode project
* The html URL in the browser is `http://localhost:40081/blueprint/servlet/page/mycustomer-de/service/myproject`
* The above JS file is included with this within this html (The `production.js` is registered within the CMS so the file path is different from above, anyway the script below is what the browser "sees" actually in the html markup):
```html
<script type="text/javascript" src="/blueprint/servlet/resources/themes/myproject/concat/production.js"></script>
```
Now what should I enter as my `webRoot` in my launch.json below so that I could set breakpoints in the production.js within VSCode? 
```json
{
  "name": "Launch localhost",
  "type": "firefox",
  "request": "launch",
  "url": "http://localhost:40081/blueprint/servlet/page/mycustomer-de/service/myproject",
  "webRoot": "${workspaceRoot}"
}
```

To me it looks like in this use case it's not feasable to debug with VSCode (correct me if I am wrong).

**Comment by hbenl** [comment]
Well, the `webRoot` should point to the directory that corresponds to the `url`, so I think it should be `${workspaceRoot}/dist/themes/myproject/`. Also, if I understand this correctly, `myproject` is a directory, not a file, in this case the url needs to end in a trailing `/`:
```
{
  "name": "Launch localhost",
  "type": "firefox",
  "request": "launch",
  "url": "http://localhost:40081/blueprint/servlet/page/mycustomer-de/service/myproject/",
  "webRoot": "${workspaceRoot}/dist/themes/myproject/"
}
```

**Comment by jnachtigall** [comment]
Thanks for the reply. I couldn't get it working, anyway, it's not my project setup which is setup wierd in the first place.
