### ISSUE TITLE
Not showing exceptions

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#27]
Debugger stops alright, but it just shows the current context as if the execution was interrupted by a breakpoint. The actual Exception stays somwhere in the background

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-01/2017-01-19_02-50-42.png)

**Comment by hbenl** [comment]
This should be fixed now.

**Comment by Spown** [comment]
Thank you.

This is certainly a way to go, but other debuggers show Exceptions in their own scope above the current one. Chrome Debugger for example:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2017-01/Code_2017-01-19_18-42-49.png)
I'm not insisting (it is ok this way also), just pointing out...
