### ISSUE TITLE
saving files on start sometimes fails

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#29]
Other debuggers save all opened files before starting a debug session. I've grown so accustomed to this that I'm constantly forget to save before I want to debug with this adapter. So much that I often start searching for bugs before realizing I was just running the old code. This often becomes especially frustrating since debugger controls may cover up tabs and the file modification indicator.

Thank you.

**Comment by hbenl** [comment]
I don't understand - when I start this (or any other) debug adapter in VS Code, all opened files are saved, as you can see by looking at the file modification indicator in this screencast:
![peek 2017-01-28 19-25](https://cloud.githubusercontent.com/assets/16060807/22398814/b8d9aac4-e58f-11e6-872e-0d1ca6827d12.gif)

**Comment by Spown** [comment]
ok. then scratch that "suggestion" and paint it a "bugreport".

**Comment by hbenl** [comment]
Note that the debug adapter is not involved in saving the files, so this is most probably a bug in VS Code.

**Comment by Spown** [comment]
yeah, but I never experienced any malfunction in this regard while using node-, node2- or chrome debuggers. only vscode-firefox-debug. So it must be hindering VSCode somehow indirectly...

**Comment by Spown** [comment]
it may be because of [this issue](/Microsoft/vscode/issues/21847). Seems to work fine in Insiders.
