### ISSUE TITLE
Replying to setBreakpointsRequest (Source xxx not seen yet)

### ISSUE THREAD

**Issue by Piwakkio** [hbenl/vscode-firefox-debug#30]
Hello,

i'm developing an Angular 2 application using Webpack in Visual Studio Code and using this extension for debugging it, but with poor luck.
My launch.json look like this:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "firefox",
            "request": "launch",
            "name": "Avvia programma",
            "url": "http://localhost:4200/",
            "webRoot": "${workspaceRoot}",
            "pathMappings":[
                { "url": "webpack:///", "path": "${webRoot}/" },
                { "url": "webpack:///./", "path": "${webRoot}" },
                { "url": "webpack:///", "path": "" }
            ],
            "log": {
                "consoleLevel": {
                    "PathConversion": "Debug",
                    "default": "Debug"
                }
            }
        }
    ]
}
```
But when i launch the debug my breakpoint become gray (conversion between file path and URL [as you suggest](https://github.com/hbenl/vscode-firefox-debug#troubleshooting)).
The debug output seems to indicate that the source file could not be found:
>INFO |002.149|PathConversion: 'webpack:///./' => 'd:/Progetti/AngularJS/quickstart'
>INFO |002.149|PathConversion: 'webpack:///' => ''
>INFO |002.149|PathConversion: 'http://localhost:4200' => 'd:/Progetti/AngularJS/quickstart'
>INFO |002.149|PathConversion: 'file:///' => ''
>DEBUG|004.680|FirefoxDebugAdapter: Setting 1 breakpoints for d:\Progetti\AngularJS\quickstart\src\app\movement\movement.service.ts
>DEBUG|004.681|FirefoxDebugAdapter: Replying to setBreakpointsRequest (Source d:\Progetti\AngularJS\quickstart\src\app\movement\movement.service.ts not seen yet)
>DEBUG|004.681|FirefoxDebugAdapter: Setting 1 breakpoints for d:\Progetti\AngularJS\quickstart\src\app\movement\movement-form.component.ts
>DEBUG|004.681|FirefoxDebugAdapter: Replying to setBreakpointsRequest (Source d:\Progetti\AngularJS\quickstart\src\app\movement\movement-form.component.ts not seen yet)
>DEBUG|004.704|FirefoxDebugAdapter: Setting exception filters: ["all"]
>DEBUG|004.779|FirefoxDebugAdapter: 0 threads

The problem is, the path is correct. Maybe a problem with folder permission? Running on Windows 7 SP1.

Any helps appreciated.

**Comment by hbenl** [comment]
`Source ... not seen yet` is normal: it just means that the debug adapter received breakpoints from VS Code before it received the corresponding sources from Firefox - this always happens in the startup phase and the breakpoints will be sent to Firefox later.
So the logs you posted are not enough yet for me to figure out why it's not working - please post all the log messages from the `PathConversion` logger (I probably don't need any other log messages, so you can remove `"default": "Debug"` from your log configuration if you want).

**Comment by Piwakkio** [comment]
I attach the file with the output since it's quite verbose.
[ff-adapter-debug.txt](https://github.com/hbenl/vscode-firefox-debug/files/792529/ff-adapter-debug.txt)

Anyway even if i'm still unable to make my application stop on the breakpoint after your explanation and re-starting my app i'm starting to belive it's unrelated with this extension since the two file i'd like to debug seems to being correctly linked:
>DEBUG|009.217|PathConversion: Converted url webpack:///src/app/movement/movement-form.component.ts?3c34 to path d:\Progetti\AngularJS\quickstart\src\app\movement\movement-form.component.ts
>DEBUG|009.224|PathConversion: Converted url webpack:///src/app/movement/movement.service.ts?3039 to path d:\Progetti\AngularJS\quickstart\src\app\movement\movement.service.ts

and the breakpoint appears red as expected.

**Comment by hbenl** [comment]
If the breakpoint appears red then it has been successfully set in Firefox, so you should be able to break on it.
When do you expect the breakpoint to be hit: immediately after the page is loaded or later as a result of some user interaction (like clicking a button)? If it should be hit immediately then you may have to click the reload button in Firefox because the breakpoint may have been set in Firefox after the script was already executed.
Have you tried with Firefox' built-in debugger or the Chrome debugger for VS Code?

**Comment by Piwakkio** [comment]
The breakpoint is on the submit of a form, so there should not be the need for reloading. Anyway i tried refreshing the page but nothing changed.
After making some minor change to the code i discovered that the breakpoint does fire after all, but not where i whould have expected. As i said the breakpoint is on the submit, but fires when the user modify the form and trying to follow the execution (F10) lead me to strange place (other methods) and the console.log() at the end of the subit does not get printed in the console.

The same behaviour happen in the Firefox debugger, so the problem definitely seems to be unrelated to the extension.
I close the issue because i'm quite confident that it's more related with my poor understanding of Angular 2 and/or Webpack than the extension itself :)
Thanks for the support!
