### ISSUE TITLE
No scopes memebers visible in the Inspector

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#34]
![](https://drive.google.com/uc?id=0B-OJBofmehO3enMxT1JRNDFfbDQ)

**Comment by Spown** [comment]
ok, I've noticed that 1 in about 3 sessions it does kinda work. For example now I have ``Object:Window`` but this intermediate ``Block`` (which should be the global script's scope) is empty, despite [having one variable](/Spown/vsc_ff_debug_test_webapp/blob/compoun_bselector_bug/static/js/index.js#L2).

**Comment by hbenl** [comment]
This is due to [Firefox bug 1249962](https://bugzilla.mozilla.org/show_bug.cgi?id=1249962). In the new release an error message is shown when an object can't be inspected due to this bug.
