### ISSUE TITLE
window is undefined

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#36]
![](https://drive.google.com/uc?id=0B-OJBofmehO3eHg1a2cxZnZoUFE)

probably related to #34

**Comment by Spown** [comment]
needless to say evaluatin says otherwise
![](https://drive.google.com/uc?id=0B-OJBofmehO3a3Y0RV9nTGtoR0U)

**Comment by hbenl** [comment]
This is fixed in the latest release.
