### ISSUE TITLE
Debugger doesn't respect Uncaught Exceptions option

### ISSUE THREAD

**Issue by mtycholaz** [hbenl/vscode-firefox-debug#37]
I have the "Uncaught Exceptions" disabled, but the debugger is still breaking on DOMExceptions within jQuery. I would expect that exceptions of this kind would be ignored since I don't have the option enabled.

![image](https://cloud.githubusercontent.com/assets/3585379/25864350/5589a412-34ac-11e7-99c9-60055a455383.png)

**Comment by hbenl** [comment]
Were the Exception breakpoints already disabled when you started the debugger or did you disable them while it was running? If you disabled them while it was running, could you try disabling them before starting the debugger to see if it makes any difference?

**Comment by hbenl** [comment]
I think I have found (and fixed) the problem.
