### ISSUE TITLE
is legacy addon with restart-required XUL supported?

### ISSUE THREAD

**Issue by ewwink** [hbenl/vscode-firefox-debug#38]
I want to debug legacy addon with addon restart-required XUL but breakpoint always grayed, can you confirm if it supported or not?

the addon: 
`https://addons.mozilla.org/firefox/downloads/file/492548/x_notifier_for_gmailhotmailyahooaol-3.5.23-fx+sm+tb.xpi`

from mozilla
`
The Add-on Debugger is not available for restart-required XUL overlay add-ons. To debug add-ons like that, use the Browser Toolbox instead.`

**Comment by hbenl** [comment]
Yes, debugging XUL overlay addons is supported. I tried with your addon and could debug it using the following launch configuration:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch addon",
            "type": "firefox",
            "request": "launch",
            "addonType": "legacy",
            "addonPath": "${workspaceRoot}"
        }
    ]
}
```
Note that breakpoints will remain grayed until the javascript file is loaded by Firefox, which is done on demand, i.e. some files are only loaded when you interact with the corresponding part of your addon.
Try setting a breakpoint in `components/Main.js`, which is one of the files that are loaded immediately on startup.

**Comment by ewwink** [comment]
thanks it work, previously I'm using

```
{
  "name": "Attach",
  "type": "firefox",
  "request": "attach",
  "addonType": "legacy",
  "addonPath": "${workspaceRoot}"
}
```
or
 ```
{
  "name": "Launch addon",
  "type": "firefox",
  "request": "launch",
  "reAttach": true,
  "addonType": "legacy",
  "addonPath": "${workspaceRoot}",
  "keepProfileChanges": true
}
```

**Comment by hbenl** [comment]
FYI: both of your configurations could only work if you installed your addon manually in the Firefox profile directory every time before starting Firefox, because (unlike restartless addons) XUL overlays can't be installed through the Firefox debugger protocol - and if you use `"type": "attach"` or `"type": "launch", "reAttach": "true"` the debug adapter will try to use that installation method.
