### ISSUE TITLE
url parameter used in the path mapping

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#43]
![](https://drive.google.com/uc?id=0B-OJBofmehO3cmh2SkZsWUxtc0k)
so, as the description of the ``url`` property suggests it should only affect the page that is shown on the debugger start. In the Readme however it says _"... a url and a webRoot property. These properties are used to map urls to local files ..."_ (its _an_ url btw)

Normally I would have something like this in the launch config:
```
            ,"url": "http://project.com/"
            ,"webRoot": "${workspaceRoot}"
```

But if I want the debugger to open lets say on a page ``http://project.com/item/572eaee7242315080fcb0720/edit`` - because I don't want to manually navigate to this page every time - I would put it in the ``url`` property and still assign ``"webRoot": "${workspaceRoot}"``. All local mappings would fail, since
```
INFO |000.743|PathConversion: 'http://project.com/item/572eaee7242315080fcb0720' => 'd:/Projects/project.com'
```
Notice how it also lacks ```/edit``` part from the launch config.

So then I would try
```
            ,"url": "http://project.com/item/572eaee7242315080fcb0720/edit"
            ,"webRoot": "${workspaceRoot}"
            ,"pathMappings": [
                {
                    "url": "http://project.com/",
                    "path": "${workspaceRoot}/"
                }
            ]
```
and get 

```
INFO |000.683|PathConversion: 'http://project.com/' => 'd:\Projects\project.com/'
INFO |000.683|PathConversion: 'http://project.com/item/572eaee7242315080fcb0720' => 'd:/Projects/project.com'
```
with this setup it does work, however I can see how this can easily lead to conflicts.

I think the ``url`` property should either only handle opening a page on startup and not be used in the path mapping or only ``{protocol}://{domain}`` parts of the url should be used, however in the later case you can never be sure that url is a proper url with protocol and domain parts to transform it this way. So I would suggest to ditch it completely and only use ``pathMappings``. For legacy reasons if the user hasn't specified ``pathMappings``, but only configured ``url & webRoot`` - ``pathMappings`` would be auto-populated with these values, but if the user has had specified ``pathMappings`` with at least 1 entry - ``webRoot`` would be ignored and ``url`` would only affect the starting page.

**Comment by hbenl** [comment]
While I don't think it will lead to conflicts (manually specified `pathMappings` always override those that are auto-generated), it's definitely confusing.
My plan is to make `webRoot` optional if `pathMappings` are specified. I won't ignore `webRoot` though, because that could also be confusing.

**Comment by Spown** [comment]
> For legacy reasons if the user hasn't specified pathMappings, but only configured url & webRoot - pathMappings would be auto-populated with these values

> My plan is to make webRoot optional if pathMappings are specified. I won't ignore webRoot though

same result in the end basically.

**Comment by hbenl** [comment]
implemented in the latest release
