### ISSUE TITLE
Launch firefox with installed add-ons

### ISSUE THREAD

**Issue by Wavum** [hbenl/vscode-firefox-debug#45]
Is it possible to launch firefox with installed add-ons?

**Comment by hbenl** [comment]
Yes, you can use the `profile` configuration property for that. Add `"profile": "default"` to your launch configuration to start Firefox with a copy of your default profile (including the add-ons you have installed there).

**Comment by victorferreira** [comment]
I tried the recommendation above but it's not working for me. I can launch the browser in private mode, but can't use any add-ons. I already made sure the add-on I want to use is allowed in private mode. Here's my configs"

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch localhost",
      "type": "firefox",
      "request": "launch",
      // "reAttach": true,
      "url": "http://localhost:3000/",
      "webRoot": "${workspaceFolder}",
      "profile": "default",
      "firefoxArgs": ["-private-window"]
    }
  ]
}
```

What am I doing wrong?

**Comment by hbenl** [comment]
@victorferreira Sorry, I can't reproduce your issue: I tried adding your `profile` and `firefoxArgs` settings to my `launch.json` and got a private window with add-ons.

**Comment by victorferreira** [comment]
What happens if you start debugging and already have an instance of Firefox running? Does it start a new instance?

<img width="67" alt="image" src="https://user-images.githubusercontent.com/645805/81696355-2cde4680-943a-11ea-8bde-fc416adc8af0.png">

>  This is my Dock


I always get a new instance of Firefox, which is, I guess, what suppose to happen since I'm using `launch`. But I'm not getting it to load with my add-ons even if I don't use `-private-window`. I tried removing the `profile` key but no success either.

I don't know what else I could try.

**Comment by hbenl** [comment]
I may have found out why it's not working for you: I used the developer edition of Firefox (which is automatically used if you have it installed in its default location) and that works. But when I switch to the regular edition of Firefox, the add-ons are not loaded in the Firefox window launched by the debugger.
So try with Firefox developer edition. If that also doesn't work, try using an [attach configuration](https://marketplace.visualstudio.com/items?itemName=firefox-devtools.vscode-firefox-debug#user-content-attach).

**Comment by vegerot** [comment]
@hbenl I am trying this with Firefox Dev Edition and it does not work for me.  Btw, when I say `"profile": "default"`, where is that default profile located?  I could try manually specifying the path to that

**Comment by vegerot** [comment]
SOLUTION FOR OTHER PEOPLE WITH MY ISSUE:
` "profile": "dev-edition-default", `
Steps:
1. Go to `about:profiles` in firefox
2. find the profile whose name you want
3. put that in the `profile` field.

For me that profile was 
`"profile": "dev-edition-default",`
