### ISSUE TITLE
pathMappings in attach mode

### ISSUE THREAD

**Issue by Angelinsky7** [hbenl/vscode-firefox-debug#46]
Hi,
can you explain me why in [configuration.ts](https://github.com/hbenl/vscode-firefox-debug/blob/888fd7dce770f4388399d0bd80cf466a8cea8a88/src/configuration.ts) @ line 75 you don't use the path mappings given by the launch.json ?

if i add this code : (that come from the line 56 in the `config.request === 'launch'` branch) after the line 75 in the else branch, i can then set breakpoint in my webpack project... 
`
if (config.pathMappings) {
    pathMappings.push(...config.pathMappings);
}
`

There is maybe a good reason but i cannot see why you would set different configuration between the 2 modes...

**Comment by hbenl** [comment]
Nope, no good reason - just a stupid mistake.
Thanks for reporting this, I've just published a fixed version.
