### ISSUE TITLE
random undefined error popup 

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#49]
![](https://drive.google.com/uc?id=0B-OJBofmehO3NTd0ZnVyT3M1anc)
Occurs randomly on Step Over. Probably happened 3 times today. I see no pattern. Sometimes happens several times in a row. Other times works fine. In different places and different scripts.

**Comment by Spown** [comment]
VSC's devtools console:
![](https://drive.google.com/uc?id=0B-OJBofmehO3OUZrdW95azVsZ2M)

**Comment by hbenl** [comment]
The stacktrace from VS Code's devtools suggests that the exception occurs in the "Document This" extension at https://github.com/joelday/vscode-docthis/blob/48e7c3bd32709c75744e53a830da4c2f8022da70/src/extension.ts#L58, where `editor` seems to be `undefined`.

**Comment by Spown** [comment]
Ok, I somehow overlooked it. I'll open an issue there. However why does it occur only while debugging with this debugger and only on resuming the execution/stepping forward?

**Comment by hbenl** [comment]
> However why does it occur only while debugging with this debugger and only on resuming the execution/stepping forward?

... *and* only sporadically...
I have no idea, anyway the "Document This" extension seems to assume that `vscode.window.activeTextEditor` is always defined, but the VS Code documentation states that it can be `undefined`.
