### ISSUE TITLE
How to debug a web app running in an another VSCode instance?

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#5]
Firstly I have to say that this extension has a potential of becoming on of the most important VSC extensions, sadly either I don't get how to make it work with my project or there is a big problem with it...

So, I have a node.js Express web app that I develop&debug with VSCode. And immediately I have a problem placing launch config for client side debugging in the same folder. It would have been nice being able to debug client-side and server-side scripts in the same IDE instance, but afaik VSCode allows only one debugger at a time, and since you can't open the same folder/project twice with VSCode - I tried to nest it:

```
webapp.dev/
|-.vscode/    - express app configs
|-static/
  |-js/
    |-.vscode/    - vscode-firefox-debug configs
    |-index.js
|-webapp.js
```
and I used the following ``launch.json`` in vscode-firefox-debug configs folder
```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch index",
            "type": "firefox",
            "request": "launch",
            "url": "http://webapp.dev", //localhost actually, domain adssigned locally in hosts file
            "webRoot": "D:/Projects/webapp.dev",
			"profile": "VSCodeDebugode" // devtools.debugger.remote-enabled, devtools.chrome.enabled, devtools.debugger.workers, devtools.debugger.prompt-connection are set as suggested
		}
	]
}
```
Theoretically it should work, since my express static paths resolve also to ``static/js/``. So When i try to do something in, for example, ``static/js/index.js``, like setting a breakpoint - I get 

```cmd
WARN |007.119|FirefoxDebugSession: Can't convert path d:/Projects/webapp.dev/static/js/index.js to url
```

BTW, notice how the error states ``d:/...`` and my config has ``D:/...``. If I also use ``d:/`` in the config - debugger doesn't even recognize the ``static/js/index.js`` file (breakpoints are gray and no errors on setting them). Adding terminating ``/`` doesn't help either. 

I think the problem is that there is no ``.html`` file under ``webRoot``. There is no, because html is generated with a templating engine and cached in-memory only.

So is this even possible? If so, how? If not - consider it a feature request: maybe an option to ignore html and watch only for js?

Also, it is stated in the readme that ``devtools.debugger.remote-enabled, devtools.debugger.prompt-connection`` are only needed for ``attach``, but without ``devtools.debugger.remote-enabled`` the ``launch`` request won't work either. I think you should move this table in the #Starting section.

Thanks

**Comment by hbenl** [comment]
So what is the url for the file `webapp.dev/static/js/index.js`? Is it `http://webapp.dev/static/js/index.js`?

The fact that your html is generated shouldn't make any difference, since html files are already ignored.

Also, I will update the documentation to make it clear that the Firefox preferences also have to be set in `launch` mode if you use your own Firefox profile for debugging. The default for `launch` configurations is to let the debug adapter create the profile, in this case you don't have to set those preferences yourself.

**Comment by Spown** [comment]
yes, the url is ``http://webapp.dev/static/js/index.js``

**Comment by hbenl** [comment]
Hmm, in this case I would expect your launch configuration with `url` set to `http://webapp.dev/` and `webRoot` set to `d:/Projects/webapp.dev` (or maybe `d:/Projects/webapp.dev/`) to work - note that it needs to be `d:/` instead of `D:/` *and* the url must end with a `/` - maybe you haven't tried this combination yet?

**Comment by Spown** [comment]
just tried, nothing different from my original entry
```js
            "url": "http://webapp.dev/",
            "webRoot": "d:/Projects/webapp.dev/",
```
nothing happens. Breakpoints are gray and no reaction whatsoever
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-07/Code_2016-07-26_11-23-26.png)
and nothing except Firefox forwarded messages in the console...
 
When I use ``D:/`` however...
```js
            "url": "http://webapp.dev/",
            "webRoot": "D:/Projects/webapp.dev/",
```
I get a reaction:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-07/Code_2016-07-26_11-27-12.png)
but still...
```
...
Unknown property 'user-select'.  Declaration dropped.
WARN |008.616|FirefoxDebugSession: Can't convert path d:/Projects/webapp.dev/static/js/index.js to url
```
in the debug console

**Comment by hbenl** [comment]
OK, I'll have to reproduce this to see why it's not working.
If you could create a little sample project (or make your project available to me), that would be very useful.

**Comment by Spown** [comment]
My project is not even on github, but I'll try to repro it on a sample.

**Comment by Spown** [comment]
here [vsc_ff_debug_test_webapp](/Spown/vsc_ff_debug_test_webapp), wish you luck

**Comment by hbenl** [comment]
Thanks, with your sample I found out what's wrong:
`url` must end with a `/` (unless it's a file url like e.g. `http://server/index.html`) and `webRoot` must *not* end with a `/`.
Obviously I'll have to make the handling of trailing slashes more robust and/or document it better, but with this setting the debug adapter should work with your project.

**Comment by Spown** [comment]
>url must end with a / (unless it's a file url like e.g. http://server/index.html) and webRoot must not end with a /.

so I just tried with the sample:
```js
            "url": "http://127.0.1.3/", //url must end with a /, check
            "webRoot": "D:/Projects/vsc_ff_debug_test_webapp", // webRoot must not end with a /, check
```
and it still doesn't work...

**Comment by hbenl** [comment]
Oh, sorry, you'll also have to use `d:/` instead of `D:/`.

**Comment by Spown** [comment]
Yey! It does indeed work, thanks!

**Comment by hbenl** [comment]
:) Great!
I'll fix the filepath-to-url mapping code soon so others won't stumble into these problems. Thanks for the bugreport and the sample app!

**Comment by Spown** [comment]
also, I hope I'm not asking too much, can you ensure that paths get properly resolved in case of something like
```js
"webRoot": "${workspaceRoot}/../..",
```

**Comment by hbenl** [comment]
Good idea, I'll do it.

**Comment by Spown** [comment]
Thanks, I use [upath](https://github.com/anodynos/upath) for that matter, btw.

**Comment by hbenl** [comment]
I have just released a new version which
- resolves webRoot paths like "${workspaceRoot}/../.." properly
- accepts a webRoot with a trailing `/`
- documents the need for the url to end with a trailing `/` if it points to a directory
- documents the need to configure Firefox for remote debugging even in launch configurations if the user specifies his own Firefox profile
- has configurable diagnostic logging and documents how to configure the extension to output messages about conversions between paths and urls

This should make the experience more pleasant for other users. Thanks again for the bugreport.

**Comment by Spown** [comment]
hi, thanks for the update!

but it still looks like at least ``webRoot`` path expects the drive letter in lower case, i.e. ``d:/...`` works while ``D:/...`` doesn't

**Comment by hbenl** [comment]
Yes, you're right. I didn't want to mess with the user's configuration (automatically lower-casing drive letters) because if there is a setup where VS Code expects an upper-case drive letter I would break the user's configuration. Anyway, now that the webRoot path is normalized, the need to manually enter an absolute path should be gone, since only webRoot paths that are relative to the workspace make sense and they can now be entered like `${workspaceRoot}/..`.
