### ISSUE TITLE
Date type is uninspectable

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#52]
![](https://drive.google.com/uc?id=0B-OJBofmehO3djdiYzlEUDZGVk0)
![](https://drive.google.com/uc?id=0B-OJBofmehO3RzJIRVFjNWVMWHM)

have to eval it in console to actually see the value...

Would be nice to see something like ``someVar: Date {Sat Oct 14 2017 00:33:19 GMT+0200}`` instead of just ``someVar: Date``

Thank you.

**Comment by hbenl** [comment]
I noticed that `Date` objects also have no inspectable properties in the Node and Chrome debuggers - but those have an object preview feature (highlighted in the screenshot below) that also shows the value of `Date` objects.
![preview](https://user-images.githubusercontent.com/16060807/31584782-5418c032-b1b5-11e7-87a6-429c334e8783.png)
I'll add the object preview feature soon.

**Comment by hbenl** [comment]
Just published version 0.17.0 which contains the object preview feature.
