### ISSUE TITLE
additional break before leaving a function scope

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#53]
There is one additional break between return line execution and exiting the function scope. After landing on return line the first Step Over doesn't seem to do anything - only the second one yields the Return Value for the inspection. These steps should be fused or the first one should be jumped over - only the second one is of value.
![](https://drive.google.com/uc?id=0B-OJBofmehO3djgtUnEzc0FJd3c)

Thank you.

**Comment by hbenl** [comment]
This behaviour comes from the Firefox debugger and I don't want to try to modify Firefox' behaviour. So if this really annoys you, you'd have to open a bug report for Firefox. Anyway you can get the return value immediately if you use "Step Out" instead of "Step Over".
