### ISSUE TITLE
How do I set a custom firefox executable?

### ISSUE THREAD

**Issue by RustyRaptor** [hbenl/vscode-firefox-debug#54]
SOLVED
As answered below: 

> The debug adapter doesn't do tilde expansion, you'll have to configure the executable path without ~, e.g. /home/rustyraptor/Downloads/firefox/firefox

So just use the full path without using a ~ to indicate the home folder. 

 
________________________________________
When I set 
```
"firefoxExecutable": "~/Downloads/firefox/firefox",
```
It doesn't seem to work. It gives me 
```
Couldn't find the Firefox executable. Please correct the path given in your launch configuration.
```

I am absolutely sure that's the path to the executable. I can run it in terminal just fine. 
I asked the same question on vscode-ff-debug 

Here is my full launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "firefoxExecutable": "~/Downloads/firefox/firefox",
            "name": "Launch index.html",
            "file": "${workspaceFolder}/index.html"
        }
    ],
    "compounds": []
}
```

**Comment by hbenl** [comment]
The debug adapter doesn't do tilde expansion, you'll have to configure the executable path without `~`, e.g. `/home/rustyraptor/Downloads/firefox/firefox`.

**Comment by RustyRaptor** [comment]
That works. I should have to thought to try that. Thanks .
