### ISSUE TITLE
Ionic 3 project

### ISSUE THREAD

**Issue by jQrgen** [hbenl/vscode-firefox-debug#55]
Hey

I'm trying to set up this addon for an ionic 3 project. Not sure how to proceed

config:
 ```json
     {
            "name": "Launch index.html",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost/src/index.html",
            "webRoot": "${workspaceFolder}"
        }
```

I get this error when i launch: 
![screen shot 2017-11-11 at 15 56 50](https://user-images.githubusercontent.com/3964957/32690554-f8b40702-c6f8-11e7-8328-551983c791df.png)

**Comment by hbenl** [comment]
That's weird, it means that the debug adapter found the Firefox executable (otherwise you'd get a different error) but starting it doesn't seems to work. Does Firefox start at all when you try to debug? If so, how long does it take for Firefox to start and how long until you get the error message?

**Comment by ChrisTutorials** [comment]
I'm not sure but you could try running Ionic Serve and then attach Firefox Debugger with this configuration

`        {
            "type": "firefox",
            "request": "attach",
            "name": "Attach",
            "host": "localhost",
            "port": 8100
        },`

Ionic works on port 8100 by default

**Comment by hbenl** [comment]
No reply -> closing
