### ISSUE TITLE
Can't convert url [...] to local path

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-firefox-debug#6]
Apparently the adapter has problems debugging remote scripts.
```
WARN |005.361|FirefoxDebugSession: Can't convert url https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js to local path
```
Steps to repro;
1. [vsc_ff_debug_test_webapp](/Spown/vsc_ff_debug_test_webapp)
2. start the debug session
3. set a breakpoint
4. reload the page in the Firefox

If I try to ```step over``` further it opens a unnamed tab with the script
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-07/Code_2016-07-27_18-24-23.png)
and I get ithis in the console 
```
No such actor {"type":"object","class":"Window","actor":"server2.conn0.pausedobj520","extensible":true,"frozen":false,"sealed":false,"ownPropertyLength":725,"preview":{"kind":"ObjectWithURL","url":"http://127.0.1.3/"}}
```

**Comment by hbenl** [comment]
The warning you're seeing is just telling you that there is no local file for this url - which is correct.
When you step into this file it will be displayed anyway, I guess I could give the tab for this file a name.
The final error message you're seeing ("No such actor...") is coming from [a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1249962) (note that the bug report is describing only one situation that triggers the bug).

So I'm not sure if there really is a bug in the adapter here. Was it just the messages in the console that got you thinking there was a bug? Or did you expect a different behaviour?

**Comment by Spown** [comment]
aha, ok... I thought ``no such actor`` thing was a part of the problem, since it always occampanied the warning... Speaking of which, the warning is a problem on its own, regardless. JQuery example is not so bad, but in my actual project this (or similar) warning:
```
WARN |014.448|FirefoxDebugSession: Can't convert url https://api-maps.yandex.ru/2.1.42/combine.js?load=0e9r0l;r16))9t1_191!)*)!1,9u)(1;1j9x1Q1I5Y$H18555$0b0f9W2x9S9T9Y91922D9U2B9X0x0r2b9B9C9E9F9G9K2g9L2l9N2o),):);)@9O9P2r2O2R2X2023265*989699299$9_9.9*9:952-2!2)9;2:0m9j9q2q2z2J3a)i)j)q)z)Q)I3d3g3k3n3r9Q9z3t1y1D6e2(5z3w3A9J3D3N3P9Z3T,d,h,f3W,k30$b,l,a,c32,m38$f,n3$2i0d3i3.3(3:$g3q0D0S05$Y$2$5$3$6$8$9$Z$-$_$!$*,D,E,F$,$:$)$@,G,H,K,L,M$q,N,O,P$i$z@2@3@4@5$Q$I-b-c-m-n-p-r-s-u-e-f-h,R-K-E-x,T,V-y-B-C4f$k$l$m$o$p4c$r$t$u$w$x$y$C$D$F$G3J4m4p4t4w4A,o,p,r$R$B4k0M4C,s,t,u,v,w,x4F4K4M0$0)-_494V4Y4245474-0@0z1a5d_75f5h:n:o_9_$___!_*_(5l5m_,_:5o1d5r5s5u5w5x5A5C1@8m1J8D2k8$1g_@_q0t5F5L_i_z_Q_I_Z.b.c5D.h5O5T5V515N.x.y:p!K.E.F52.W.Y1m_._)3__j_J.$:r._...!.(.).:.;.q54.j.i.Q565759.J.Z!a0y!c0F0O5_5-5!5(!d!e!g:s5,5::t:u:v:w:x:y:A:B:C:D:E:F:G:H:K:L:M!h0U5@1o5i5j1r5Q1v5I1x:q!m:j:U:3:4:*:(:):,:::;:@:z:Q:J:I:Z!o;a;b;c;d;e;f:0:2:5!B!D!s;g;h;k;l!E6b!l6f!A!F!H.k!M;m;o;n;p6k!P;t;u;s;y!U!V!X!Y!0!2!3!6!4;A;B!9!$!_6m!R;v;w6o!S;x!86p6s!!!*6u6v6x6D;O*_*R*U.n*!***)086E*,*:6F6K.v$L3).D.H6g6)$M$O6:6@6j6z6I6Z7a7d7e7g7k7n2e$P&callback_prefix=ymaps_loader to local path
```
is spawned on every debugger ``step`` action. My console looks like the Matrix screen in just couple of seconds. So if you say the adapter is working as it should, is there even any need for this warning?

**Comment by hbenl** [comment]
OK, I didn't expect so many of these messages. The warnings can be useful sometimes because they also show up when something is wrong with the filepath-to-url mapping (as in your last bug report). 
Anyway I will make these diagnostic messages configurable and disable them by default.

**Comment by Spown** [comment]
that would be nice, thnx

**Comment by Spown** [comment]
also, instead of disabling them by default, maybe just trimming or cutting query part of the url away in the message would suffice? in my case I would certainly disable it, but for normal behavior it needs just not to take to much space... Or maybe making sure that the message concerning one url is shown only once per debug session instead on every step?

**Comment by hbenl** [comment]
I have just released a new version which
- has configurable diagnostic logging and disables diagnostic logging by default
- generates names for the virtual files containing `eval()` expression
