### ISSUE TITLE
Debugging Angular application on Ubuntu

### ISSUE THREAD

**Issue by napalm00** [hbenl/vscode-firefox-debug#60]
I'm trying to debug an Angular 4 application on Ubuntu using VSCode and this extension, however the behaviour is really strange.
If I set `"sourceMaps":"client"`, then the breakpoints I set work, but only if they're not if statements or function names. If I don't set it, no breakpoints work.

For reference, here's my launch.json:
```
{
            "name": "Launch firefox",
            "type": "firefox",
            "request": "launch",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceRoot}",
            "log": {
                "consoleLevel": {
                    "PathConversion": "Debug",
                    "default": "Error"
                }
            },
            "pathMappings": [
                { "url": "webpack:///", "path": "/" },
            ],
            "sourceMaps":"client"
},
```

The diagnostics convert the webpack urls properly, but fail at the ng:/// urls (not sure what those even are?), like so:
```
INFO |003.013|PathConversion: Can't convert url ng:///PagesModule/LoginComponent.ngfactory.js to path
INFO |003.013|PathConversion: Can't convert url ng:///PagesModule/LoginComponent.html to path
```

The same project works fine using the Chrome VSCode extension.

**Comment by hbenl** [comment]
Unfortunately I couldn't reproduce this, here's what I tried:
I created a new app using the angular cli, copied your launch configuration, started the debugger, opened `src/main.ts` and set a breakpoint at line 7 (that line contains an `if` statement). Then I press reload in Firefox and the breakpoint is hit. When I change `sourceMaps` from `client` to `server`, it works just the same.
There are just 2 issues I could find:
- If I set the breakpoint first and then start the debugger, the breakpoint is shown gray, which usually means that it couldn't be activated. This is, however, just a display problem: the breakpoint does work when I press reload in Firefox, even though it remains gray. I will investigate this display bug.
- This particular breakpoint is only hit when I press reload in Firefox, but not right after starting the debug session. This is a known issue with the debug protocol: I can only send breakpoints to Firefox after a javascript file has already been loaded and started executing. By the time the breakpoint is set in Firefox, the execution is often already past that point. This issue can be somewhat mitigated by setting `"reAttach": true` in your launch configuration: After the first debug session, Firefox will be kept running and re-used for further debug sessions. In these debug sessions, the breakpoint will be hit without the need to press reload in Firefox.

Could you give me access to your project or a little test project for reproducing the issue?

By the way, the `ng://` URLs are created by Angular for files generated by Angular. In general they can't be mapped to any of your source files, but that shouldn't affect debugging.

**Comment by napalm00** [comment]
I see, I think the problem is with Angular events. 
I was setting the breakpoint in an `(click)` listener callback function and that seems to trigger the bug. If I set the breakpoint to a function that's called on execution (like the `environment.production` if check in `main.ts`) then it works properly.

**Comment by hbenl** [comment]
* I could reproduce the breakpoints not working on if statements. This is a Firefox issue, as I can also reproduce it in the Firefox devtools ([bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1435519))
* I could still not reproduce the breakpoints not working with server-side sourcemap handling. Here's what I tried:
```ts
@Component({
  selector: 'app-root',
  template: `
    <button (click)="click()">Click me</button>
  `
})
export class AppComponent {
  click() {
    if (true) {
      console.log('Foo! Bar!');
    }
  }
}
```
Breakpoints in this example work exactly the same whether I set `sourceMap` to `client` or `server`

* I found (and will fix) the bug that caused breakpoints to remain gray if they were set before the start of the debugging session

**Comment by hbenl** [comment]
The bug that I could reproduce has been fixed, the rest is either upstream (Firefox) or not reproducible.
