### ISSUE TITLE
Cannot debug webextension

### ISSUE THREAD

**Issue by fenuks** [hbenl/vscode-firefox-debug#61]
Hello! I tried to launch [vim-vixen](https://github.com/ueokande/vim-vixen) extension with debugger, but am unable to do so with `This debugger currently requires add-ons to specify an ID in their manifest` error. [Manifest file](https://github.com/ueokande/vim-vixen/blob/master/manifest.json) is as follows (it has addon ID specified, unless I am missing something), and this is my launch configuration.

```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Firefox addon",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "addonType": "webExtension",
            "addonPath": "${workspaceFolder}",
            "firefoxExecutable": "/usr/bin/firefox-developer-edition",
        }
    ]
}
```
I would be grateful for any hint on this (traced in source code where error is raised, but it didn't help me to understand where lies the problem). Thank you.

**Comment by hbenl** [comment]
This is actually a bug: I use the firefox-profile library to find the addon ID, but that library thinks this is a jetpack addon because there is a `package.json` file...
I'm working on a fix, in the meantime you can work around this issue by adding `"id": "vim-vixen@i-beam.org"` to your package.json.
Hint: you will also need a path mapping in your `launch.json` (because the default webpack path mappings of this adapter don't work for addon projects):
```
            "pathMappings": [
                {
                    "url": "webpack:///",
                    "path": "${workspaceFolder}"
                }
            ]
```

**Comment by fenuks** [comment]
Thank you so much, for both workaround and hint! It helped. :-)

**Comment by hbenl** [comment]
FYI: I just published a fixed version, so you can remove that workaround again.

**Comment by fenuks** [comment]
Thank was fast! Thank you for letting me know.

**Comment by Gozala** [comment]
I am running into this issue, I tried also adding "id" in package.json as it was suggested [in comment above](https://github.com/hbenl/vscode-firefox-debug/issues/61#issuecomment-360980353) but I still seem to get same error.

**Comment by hbenl** [comment]
That workaround (adding `id` to `package.json`) is not necessary anymore. However, the extension (currently) still requires `applications.gecko.id` to be defined in `manifest.json` (like [here](https://github.com/ueokande/vim-vixen/blob/f467e9bf20fd75723d83425b9c93b295161639f1/manifest.json#L12)).
I'll have look if I can get rid of this (outdated) requirement.

**Comment by hbenl** [comment]
Just published an update that removes the requirement for an extension ID, so now it should work out of the box.
Please tell me if it does work for you.

**Comment by hbenl** [comment]
I guess it works now.
