### ISSUE TITLE
[Question] Debugging is really slow with webpack

### ISSUE THREAD

**Issue by Angelinsky7** [hbenl/vscode-firefox-debug#62]
Hi,
The debugging with firefox is really slow, like 5 sec. between each step (F10) with every of my webpack project.
You can test it with the angular-cli here : https://angular.io/guide/quickstart
Here's my config :
```
{
            "type": "firefox",
            "request": "attach",
            "name": "Attach to Firefox",
            "webRoot": "${workspaceFolder}/src",
            "url": "http://localhost:3000",
            "pathMappings": [{
                "url": "webpack:///src",
                "path": "${workspaceFolder}/src/src"
            }]
        },
```
the same config with the chrome debug is working really fast... (but i've got other issue with it and i really prefere Firefox)

Firefox Developper Edition version : 59.0b11 (64-bit)
I've done the configuration in about:config like the readme...

Could you help me understand what i need to configure to have correct performance ?
Thanks for you amazing work !

**Comment by hbenl** [comment]
I am aware that debugging webpack projects is quite slow.
You could try debugging your project in the Firefox devtools and see if that is faster - in my experience it is only a little bit faster but still much slower than Chrome. This shows that the performance bottleneck is in Firefox.
You could also try adding `"sourceMaps": "client"` to your launch config, in the past this improved performance a little bit in some setups.
I'd be interested to hear your results.

**Comment by Angelinsky7** [comment]
@hbenl thanks for your input, i'll make some test and report back... it's really a shame that Firefox is so slow, it makes debugging impossible against the perf of chrome...

**Comment by JSteitz** [comment]
SourceMap clients helps a lot.

**Without `sourceMaps` option**
Mapping is very slow, you can watch how it does 5 - 10 files at the same time.
Also the CPU goes up for vscode and firefox each 150% and up (on my mac).
Step over or any other step command can take up to 1 minute to react.

**With `sourceMaps` option**
File mappings are done instantly.
CPU stayes were it is and does not rise.
Commands are taking the same time as firefox itself takes.

The only problem I have now is currently that Breakpoints on function calls are not stopped.
I will make later a minimal test for that and create a new ticket.

**Comment by hbenl** [comment]
I've changed the default to `"sourceMaps": "client"` in 1.6.0
