### ISSUE TITLE
Cannot debug CRA TypeScript App 

### ISSUE THREAD

**Issue by chimon2000** [hbenl/vscode-firefox-debug#63]
I have an app that I have started converting to TypeScript, and I am unable to debug it in Firefox.  

I have followed the instructions for enabling debugging in Firefox

VS Code Version: 1.20.1
Firefox Version: 59.0b12
Mac Version: Sierra

I have added an example of my scenario [here](https://github.com/chimon2000/vscode-firefox-debug_issue_63)

**Comment by chimon2000** [comment]
From some additional diagnosis, it looks like this issue is specific to the version of VS Code.  Rolling back to 1.19.x resolves the issue.

**Comment by hbenl** [comment]
It works for me with the following configuration:
```
    {
      "type": "firefox",
      "request": "launch",
      "reAttach": true,
      "name": "Launch Firefox",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}",
      "pathMappings": [
        {
          "url": "http://localhost:3000/",
          "path": "/"
        }
      ]
    }
```
- why do you try to use an `attach` configuration? Manually setting up Firefox for debugging is a lot more error-prone than letting the debug adapter do that for you (by using a `launch` config)
- your debug configurations use the url `http://localhost:3002`, but `npm run start` creates a devserver running on port `3000`, not `3002`
- CRA configures webpack to use URLs like `http://localhost:3000/absolute/path/to/your/project/something.tsx`, the `pathMappings` shown above are needed to map these URLs to the corresponding files in your project: I figured this out using the Loaded Scripts Explorer.

**Comment by chimon2000** [comment]
Thanks for the quick turnaround! I was able to get the app running using your example above.  Closing this issue.
