### ISSUE TITLE
Uninstall issues

### ISSUE THREAD

**Issue by andywillis** [hbenl/vscode-firefox-debug#67]
Hi. I no longer use this addon but I can't seem to uninstall it. I click uninstall, and the reload and install buttons appear, but when I reload the addon is still present and a icon says it's updating to the latest version:

![image](https://user-images.githubusercontent.com/1903595/37594481-28e57a04-2b6d-11e8-83c7-1fb5d54faeda.png)

It appears it cannot be removed :/

**Comment by hbenl** [comment]
My addon does not influence the uninstall process in any way, so please file a bug report for VS Code.
My guess is that this happens when you try to uninstall an addon while VS Code is downloading an update for that addon. You could try installing the update and then uninstalling again...
