### ISSUE TITLE
Workspace with spaces in path get translated to %20

### ISSUE THREAD

**Issue by drake7707** [hbenl/vscode-firefox-debug#68]
If my file I'm trying to debug is
`D:\Programming\JS Projects\MyProject\main.js`
then the debugger looks for
`D:\Programming\JS%20Projects\MyProject\main.js`
and then errors out with it not being able to find main.js.

**Comment by hbenl** [comment]
This is fixed in version 1.1.4 which I just published.
Thanks for the bugreport.
