### ISSUE TITLE
Breakpoints ignored at initial "launchE: Need to manually "reload" firefox once

### ISSUE THREAD

**Issue by jnachtigall** [hbenl/vscode-firefox-debug#7]
**Steps to reproduce:**

1. Have some breakpoints
2. Start with "Launch index.html" or "Launch localhost"

**Expected:**
3. VS Code stops at the Breakpoints when Firefox is launched and runs the code.

**What actually happens:**
I need to manually hit "Reload" (<F5>) in Firefox first. Then the VS debugger kicks in. It should already kick in when initially loaded.

**Comment by hbenl** [comment]
This is a weakness of the Firefox debug protocol: VSCode can't tell Firefox about breakpoints in a file before the execution of that file starts. When the request for setting breakpoints is processed by Firefox, the line for which the breakpoint is being set has already been executed.
So I can't fix this problem, but I have now documented it in the Troubleshooting section of the Readme file.

**Comment by jnachtigall** [comment]
> This is a weakness of the Firefox debug protocol

Mind opening a bug report at BMO about this?

**Comment by gerdneuman** [comment]
@hbenl Seriously, I think it would be great if you could file a bug on bugzilla.mozilla.org. I could do it, but I am sure you can better explain the technical background.

I am not assiciated with Mozilla, but filed many, many bugs for the Developer Tools. I found the Mozillians very open towards feedback. Most of the bugs were fixed or at least triaged and then fixed later. So I (as a user of your plugin) would appreciate if the original source could be fixed eventually (in some time). Or at least get the chance of fixing it. But first the upstream developers should have the chance of knowing about this problem.

**Comment by gerdneuman** [comment]
@hbenl OTOH, I would be curious how the https://github.com/devtools-html/debugger.html solves this "breakpoints can only be added at second run" issue. Wouldn't they have the same problem?

**Comment by hbenl** [comment]
@gerdneuman Well, they have the same limitation (and so does the built-in Firefox debugger), but in their case the limitation is less confusing for the user: the javascript files simply don't show up before they're run (they can't show up earlier because the debugger gets the files from Firefox and Firefox doesn't know about them until they're loaded and run). So the user can't set a breakpoint in a javascript file before it is run and hence the debugger never skips a breakpoint.

**Comment by gerdneuman** [comment]
@hbenl I see, but afaik debugger.html can also be used from within an editor or as CLI. For instance, at the React Rally there was a presentation (relevant snippet is at https://www.youtube.com/watch?v=Fk--XUEorvc&feature=youtu.be&t=2h40m32s) showing integration into emacs or using debugger.html as CLI tool. 

So I wonder how this is possible whereas the VS code debugger here is not able using the Firefox Debugger Protocol at initial start. I guess the debugger.html should have the same problems protocol wise. Pinging @jlongster if he has some insight here? Maybe there's some workaround.

**Comment by jlongster** [comment]
@gerdneuman I'm not familiar enough with VS Code to know what you mean by "initial start", but my editor integration does require an existing connection to a Firefox browser. I have the same limitation. When I connect it gets a list of all the current sources in the page and matches them with local files.

Unfortunately this is a limitation with the Firefox protocol. However, we plan to move the `setBreakpoint` request to something like the thread and allow it to take many types of patterns (URL, source id, etc). Or do whatever it takes to make this work. It shouldn't take too long, but it'll probably be a little while before we find time to do it.

**Comment by hbenl** [comment]
@jlongster That sounds great (incidentally the [documentation](https://wiki.mozilla.org/Remote_Debugging_Protocol) of the debugging protocol claims that setBreakpoint requests should be sent to the thread actor - seems like this documentation was beamed here from the future ;) ).
Is there a bug report or some other kind of tracker for this, so I can get notified when this has been implemented?
