### ISSUE TITLE
Please avoid node dependency to "natives" module

### ISSUE THREAD

**Issue by bpasero** [hbenl/vscode-firefox-debug#70]
Hi,

I am a developer on VSCode and wanted to reach out to inform you that this extension is either using or having a dependency to a node module "[`natives`](https://www.npmjs.com/package/natives)" that will soon no longer be supported in VSCode once we updated to node.js 8.x (as part of our Electron 2.0 update which is planned for the near term). 

The full graph is:

```
└─┬ unzip@0.1.11
  └─┬ fstream@0.1.31
    └─┬ graceful-fs@3.0.11
      └── natives@1.1.0 
```

It would be great if this dependency could be avoided by either not depending on it anymore or updating the dependencies to newer versions so that this module is no longer pulled in. 

As soon as any code in your extension (including `node_modules`) calls `require("natives")` we will throw an exception to prevent this module from getting loaded.

If this is just a `devDependency` and the module is never loaded in production, then you can ignore this issue and just close it!

More details in https://github.com/Microsoft/vscode/issues/47569

Thanks!
Ben
VSCode Team

**Comment by Tyriar** [comment]
Related: https://github.com/EvanOxfeld/node-unzip/issues/97

**Comment by bpasero** [comment]
A good alternative node module to `unzip` seems to be [`unzip-stream`](https://www.npmjs.com/package/unzip-stream), a fork of the `unzip` library with similar API.

**Comment by hbenl** [comment]
Thanks for the early warning, I will replace the `unzip` dependency ASAP (definitely before the next VSCode release).

**Comment by hbenl** [comment]
I have replaced `unzip` with `unzipper`, which doesn't depend on `natives`.

There is still the `gulp` package which depends on `natives`. However, `gulp` is only a `devDependency`, so that shouldn't be a problem, right? The output of `npm ls -prod` doesn't contain the `natives` module.

**Comment by Tyriar** [comment]
@hbenl that's fine, as long as `require('gulp')` doesn't happen when the extension is run you're good to go 👍

**Comment by hbenl** [comment]
Thanks for clarifying.

**Comment by bpasero** [comment]
@hbenl thanks 👍
