### ISSUE TITLE
Chokidar update broke windows file watching

### ISSUE THREAD

**Issue by Misiur** [hbenl/vscode-firefox-debug#71]
This commit broke file watching on windows - https://github.com/hbenl/vscode-firefox-debug/commit/4e6979935c810c312c80614f80ac391fe0fe0442

See https://github.com/paulmillr/chokidar/blob/master/CHANGELOG.md#chokidar-200-dec-29-2017

Paths such as `C:\\Foobar\\workspaceproject\\scripts\\**\\*.js`, and especially mixed style paths `C:\\Foobar\\workspaceproject/**/*.js` will not work.

PR: Don't merge yet, something is _still_ not right

**Comment by Misiur** [comment]
Done, I didn't notice that single-item configuration returns early.

**Comment by hbenl** [comment]
Oops, I remember seeing that Changelog entry for chokidar, but then I forgot to do something about it.
