### ISSUE TITLE
Haven't been able to make this work

### ISSUE THREAD

**Issue by jakegt1** [hbenl/vscode-firefox-debug#75]
Hi,

I have been wanting to use this debugger for a while, but every time i try and use it, it never works.

I've added debug lines for the path conversion and it says that it converts all of the relevant files, but the breakpoints stay unverified and i'm back to using the default firefox debugger.

My config is like this below, and i'm using Firefox Developer Edition.
```json
{
            "name": "Index",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost:5000/",
            "webRoot": "${workspaceFolder}\\service\\static",
            "log": {
                "consoleLevel": {
                    "PathConversion": "Debug",
                    "default": "Error"
                }
            }
}
```

Any suggestions?

**Comment by hbenl** [comment]
Do you use webpack and/or a transpiler? In that case, you have to make sure that sourcemaps are generated. Also, the default `pathMappings` may not work for your setup, in which case you'll have to add some `pathMappings` manually:
* start a debugging session
* in the "Loaded Scripts Explorer" that is shown in the Debug sidebar, find the file that you want to debug
* right-click on the directory containing that file and select "Map to local directory"
* select the corresponding local directory and click "Map to this directory"
* restart the debugging session and check if it works now

**Comment by jakegt1** [comment]
Alright, I refreshed my Firefox settings and it started working, woo.

Do wonder what broke it in the first place though. Thanks anyway!
