### ISSUE TITLE
Developer Edition is not launched over the default Firefox

### ISSUE THREAD

**Issue by x-ji** [hbenl/vscode-firefox-debug#76]
- System: Host: jx-X1 Kernel: 4.14.48-2-MANJARO x86_64 bits: 64 compiler: gcc v: 8.1.1 Desktop: i3 4.15.0.1 Distro: Manjaro Linux 17.1.10 Hakoila 
- Firefox Developer Edition path: `/usr/bin/firefox-developer-edition`
- Firefox path: `/usr/bin/firefox`

If I don't specify `firefoxExecutable`, the default version of Firefox is still launched over the Developer Edition.

**Comment by hbenl** [comment]
I was looking for `firefox-developer` but not `firefox-developer-edition`. Fixed in version 1.4.1.
Thanks for the bugreport.
