### ISSUE TITLE
Keep popups open - WebExtension debugging

### ISSUE THREAD

**Issue by rugk** [hbenl/vscode-firefox-debug#80]
Somehow we need a way to toggle the "Disable popup auto-hide" function.

The default Firefox DevTools show it, but it would be more convenient, if we could enable/disable it in VS, too.

**Comment by hbenl** [comment]
Try adding
```
"preferences": {
    "ui.popup.disable_autohide": true
}
```
to your `launch.json`. If this works, I'll add it to the documentation.

**Comment by rugk** [comment]
Oh great, I'll try that out. However, I rather thought of a button I can enable and disable.
Because when you are at the state of having a pop-up open you usually need to deselect it, to close it and retry what you wanted to do.

**Comment by hbenl** [comment]
I've just published a new version that shows the current popup auto-hide status in the status bar and toggles it when clicked. There are also new commands for changing popup auto-hide, in case someone wants to add them to his keybindings.
