### ISSUE TITLE
Best resloution to seemingly incorrect pathMappings?

### ISSUE THREAD

**Issue by cavaloni** [hbenl/vscode-firefox-debug#84]
This is an example of one of the mappings, and it looks quite strange as it is adding localhost and the whole directory in there again:

`DEBUG|001.934|PathConversion: Converted url http://localhost:8080/Users/chad.avalon/Documents/projects/ce/node_modules/moment/locale/ky.js to path /Users/chad.avalon/Documents/projects/ce/build_dev/localhost:8080/Users/chad.avalon/Documents/projects/ce/node_modules/moment/locale/ky.js`

This is happening even when I set the pathMappings explicitly and leave out any `${webRoot}` or `${workspaceFoler}`.

The current set up is as follows:

```{
            "name": "Attach to Firefox",
            "type": "firefox",
			"request": "attach",
			"url": "http://localhost:8000",
			"webRoot": "${workspaceFolder}/build_dev",
			"log": {
				"consoleLevel": {
					"PathConversion": "Debug",
				}
			}
        },
```

Using latest version of vscode with Mac osx.

**Comment by hbenl** [comment]
The PathConversion log shows that you're using port `8080`, but in the configuration you specify port `8000`.

**Comment by hbenl** [comment]
I guess this is working now...
