### ISSUE TITLE
Firefox freezes when the "sourceMaps" option is set to "server"

### ISSUE THREAD

**Issue by TheAifam5** [hbenl/vscode-firefox-debug#88]
Hey,

I noticed the problem when I used the default "sourceMaps" option in "launch.json", was always freezing, but when I switched to "client" - started working.

Firefox 62.0b20 on Windows 10
VSCode:
```
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

Regards,
TheAifam5

**Comment by hbenl** [comment]
Thanks, I'll switch the default to `client` in the next release.

**Comment by hbenl** [comment]
I've changed the default to `client` in 1.6.0
