### ISSUE TITLE
Extension cannot find Firefox Developer Edition

### ISSUE THREAD

**Issue by volkoff-pro** [hbenl/vscode-firefox-debug#89]
macOS HighSierra Version 10.13.6
Visual Studio Code Version 1.26.1
Debugger for Firefox Version 1.5.0

Firefox Developer Edition installed into default location:
/Applications/Firefox Developer Edition.app

If I try to launch debug session, I have this message:
"Couldn't find the Firefox executable. Please specify the path by setting "firefoxExecutable" in your launch configuration."

After installing regular version of Firefox, launching debug session from VS Code debugging started in regular version, not in Developer Edition.

launch.json settings:
{
      "type": "firefox",
      "request": "launch",
      "reAttach": true,
      "name": "Firefox Debug",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}/src",
      "pathMappings": [
        { "url": "webpack:///~/", "path": "${webRoot}/node_modules/" },
        { "url": "webpack:///./~/", "path": "${webRoot}/node_modules/" },
        { "url": "webpack:///./", "path": "${webRoot}/" },
        { "url": "webpack:///src/", "path": "${webRoot}/" },
        { "url": "webpack:///", "path": "" }
      ]
    }

**Comment by hbenl** [comment]
Thanks for the bug report, this is fixed in the latest release (1.6.0)
