### ISSUE TITLE
Support defaulting profile, profileDir, keepProfileChanges etc. from user specific settings

### ISSUE THREAD

**Issue by modax** [hbenl/vscode-firefox-debug#90]
Hello,

It think it would be useful to configure default values for `profile`, `profileDir`, `keepProfileChanges` and maybe other settings in user and/or workspace settings (settings.json). E.g. I might prefer to use my custom profile for debugging while other team members might not. I don't want to impose my will by adding these to lauch.json.

Thanks!

**Comment by hbenl** [comment]
Thanks for the suggestion! I've added settings that override `firefoxExecutable`, `firefoxArgs`, `profile`, `profileDir` and `keepProfileChanges`. Unlike your suggestion, the settings take precedence over the launch configuration properties (so they're not just defaults), but for your use case this probably doesn't make a difference.

**Comment by velara3** [comment]
Are docs on how to use these? I'd like to use my current profile settings when launching a debug session. Currently, whenever I launch Firefox to debug it starts out as if it has just been installed and run for the first time. All settings and preferences are lost. 

If this is a separate issue let me know and I'll create it.

**Comment by hbenl** [comment]
@velara3 Add `"profile": "default"` to your `launch.json` to make your current default profile the template for the temporary debugging profile. Alternatively you can add `"firefox.profile": "default"` to your vscode settings (if you don't want to have this setting in the project's debug configuration). Use `firefox -P` on the command line to manage your profiles.
