### ISSUE TITLE
Firefox is launched without debugging server

### ISSUE THREAD

**Issue by XuluWarrior** [hbenl/vscode-firefox-debug#95]
When I use the default launch.json and run `Launch addon`, if Firefox isn't already open, Firefox is launched but immediately stop with `connect ECONNREFUSED 127.0.0.1:6000`.

Manually launching Firefox with `--start-debugger-server` and then running `Launch addon`, works.

My example repo
https://github.com/XuluWarrior/webextensions-vsc-dev-example/tree/borderify

I am running on macOS 10.14.2 if that makes any difference.

**Comment by hbenl** [comment]
It works for me on Linux - I'll test this on MacOS tomorrow.

**Comment by XuluWarrior** [comment]
This does look like it could be a MacOS issue.  I just tried in a Windows VM and the debugger managed to launch Firefox and attach as expected.

**Comment by hbenl** [comment]
I fixed this in version 1.7.5, which I just published.
