### ISSUE TITLE
Failed fetching sourcemap

### ISSUE THREAD

**Issue by XuluWarrior** [hbenl/vscode-firefox-debug#96]
I have an example addon that uses webpack (https://github.com/XuluWarrior/webextensions-vsc-dev-example/tree/react-es6-popup).

When I set `sourceMaps` to `server` then my source maps and breakpoints work as expected.  However, when I use `client` the source maps don't work and I see the following in the logs when I enable them.

`WARN |011.679|SourceMappingThreadActorProxy: Failed fetching sourcemap from moz-extension://30d71ff4-c24a-d645-af3f-19d80874ab66/dist/popup.js.map`

**Comment by hbenl** [comment]
Thanks for providing the example, that saved me a lot of work. I've fixed this in version 1.7.5, which I just published.

**Comment by XuluWarrior** [comment]
Finally had a chance to test this and it works for me.
