### ISSUE TITLE
Breakpoint RDP breaking changes in Firefox 67

### ISSUE THREAD

**Issue by digitarald** [hbenl/vscode-firefox-debug#99]
Firefox 67 (in Nightly atm) introduced some breaking changes in the past weeks to enable [Worker Debugging](https://bugzilla.mozilla.org/show_bug.cgi?id=1520698) and improve [breakpoint locations](https://bugzilla.mozilla.org/show_bug.cgi?id=1518661) on the server. We have to believe that this project will be also affected.

Just wanted to leave a note; but need to expand this with more details on the changes and testing.

**Comment by hbenl** [comment]
I just published version 1.7.7 which implements the necessary protocol changes.
Breakpoints with a Hit Count or a Log Message don't work yet, but I'll fix that soon.

**Comment by hbenl** [comment]
@digitarald I was about to implement the missing features when I saw that the RDP spec (in `devtools/docs/backend/protocol.md`) states that the reply to `setBreakpoint` requests should contain the name of a breakpoint actor - but currently it doesn't. The disappearance of breakpoint actors from the RDP is what broke those features in the first place. Now I'm wondering: is this just a bug in the current Firefox beta and I should wait for the breakpoint actors to reappear? Should I file a bug report about this? I also noticed that paused events with `{ "type":"breakpoint" }` still contain the `actors` property (which should list breakpoint actors), but its value is usually `[null]`.

**Comment by digitarald** [comment]
I forwarded this to 2 debugger engineers who should jump in to comment.

**Comment by bhackett1024** [comment]
Breakpoint actors have been removed entirely.  Breakpoints are set or removed using messages sent to the thread actor instead.  I'll update the docs.

**Comment by jasonLaster** [comment]
Just took at your implementation, is this the relevant spot? https://github.com/hbenl/vscode-firefox-debug/blob/2c3c5efe200759b295cfde990a2daf4fdbbeefeb/src/firefox/actorProxy/source.ts#L77

Here is a bit more information about our debugger:

commands is our API layer [link][c]
thread-client is the protocol layer we most use [link][tc]

[tc]: https://searchfox.org/mozilla-central/source/devtools/shared/client/thread-client.js

[c]: https://searchfox.org/mozilla-central/source/devtools/client/debugger/new/src/client/firefox/commands.js#220-228

**Comment by jasonLaster** [comment]
@hbenl feel free to join our slack https://devtools-html-slack.herokuapp.com/. We have a #vscode room where we can discuss protocol changes / improvements

**Comment by hbenl** [comment]
@bhackett1024 Thanks for clarifying!

@jasonLaster the relevant spot is [here](https://github.com/hbenl/vscode-firefox-debug/blob/31ac3ca54660c240adb74834e2a148cedda12511/src/adapter/thread.ts#L72). I use(d) the Breakpoint actor to identify which breakpoint caused the thread to pause, I need this to support VS Code's "Hit Count" feature (where you can say "break the n-th time that this breakpoint is hit") and the "Log point" feature (but I've seen that this is now supported by Firefox itself, so I'll let Firefox do that in the future). So now I'll need to identify the breakpoint by looking at the location instead of the Breakpoint actor - but that shouldn't be a problem.

**Comment by hbenl** [comment]
> feel free to join our slack

I'll do that when I have any questions.
Thanks for the support, guys!

**Comment by hbenl** [comment]
I just published version 1.7.9, which completes support for the RDP changes in Firefox 67.
